on: [push]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        name: Publish Docs
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - run: npm install
            - run: npm run build --if-present

            - name: Publish Docs
              uses: cloudflare/pages-action@1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: bot-whatsapp-docs
                  directory: packages/docs/dist
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
